# 00__Overview.R
# Created by: Michael Sieler
# Date last updated: 2026-04-22
#
# Description:
# Driver for the 00__Overview module. Generates the GT table(s) needed by
# `Code/02__Results/00__Overview.Rmd` and saves them as a serialized bundle under
# `Results/00__Overview/Stats/`.
#
# Expected input:
# - `Data/r_objects/ps-list__*.rds` generated by preprocessing (`ps.list` must exist)
#
# Expected output:
# - `Results/00__Overview/Stats/overview__bundle.rds`

# --- Ensure project root (Sieler2026/) ----------------------------------------
init_rel <- file.path("Code", "00__Setup", "00__InitializeEnvironment.R")
if (!file.exists(init_rel)) {
  stop(
    "Set working directory to the Sieler2026 repository root, or run:\n",
    "  Rscript Code/01__Analysis/00__Overview.R\n",
    "from the project root so `", init_rel, "` resolves."
  )
}
source(init_rel)

# --- Paths --------------------------------------------------------------------
path_res_overview <- file.path(path.results, "00__Overview")
path_fig <- file.path(path_res_overview, "Figures")
path_tbl <- file.path(path_res_overview, "Tables")
path_stats <- file.path(path_res_overview, "Stats")
dir.create(path_fig, recursive = TRUE, showWarnings = FALSE)
dir.create(path_tbl, recursive = TRUE, showWarnings = FALSE)
dir.create(path_stats, recursive = TRUE, showWarnings = FALSE)

# Archive previous outputs (copy → verify → clear) so each run is clean but reproducible.
sieler2026_archive_module_outputs(
  path_res_module = path_res_overview,
  module_name = "00__Overview",
  subdirs = c("Figures", "Tables", "Stats"),
  clear_original = TRUE
)

bundle_rds <- file.path(path_stats, "overview__bundle.rds")

if (!exists("ps.list", inherits = TRUE) || is.null(ps.list$All)) {
  stop("ps.list$All not found. Run preprocessing and ensure ps.list is available in the environment.")
}

# --- Sample-count table (computed from ps.list$All) ----------------------------
timepoints <- c("T0", "T14", "T18", "T25", "T29", "T60")

ps_all <- ps.list$All
samdat <- data.frame(phyloseq::sample_data(ps_all), check.names = FALSE, stringsAsFactors = FALSE)

samdat <- samdat %>%
  dplyr::mutate(
    abx_raw = dplyr::coalesce(as.character(.data$A), as.character(.data$Antibiotics)),
    heat_raw = dplyr::coalesce(as.character(.data$T), as.character(.data$Temperature)),
    par_raw = dplyr::coalesce(as.character(.data$P), as.character(.data$Parasite)),
    antibiotics = dplyr::if_else(abx_raw %in% c("+", "1", "A+", "Exposed"), "+", "-"),
    heat_stress = dplyr::if_else(heat_raw %in% c("+", "1", "T+", "High", "High Temp"), "+", "-"),
    parasite = dplyr::if_else(par_raw %in% c("+", "1", "P+", "Exposed"), "+", "-"),
    prior_stressor_history = as.integer(dplyr::coalesce(.data$HistoryLevelNum, .data$History)),
    time_point_raw = dplyr::coalesce(as.character(.data$time_point), as.character(.data$Time)),
    time_point = dplyr::case_when(
      is.na(.data$time_point_raw) ~ NA_character_,
      grepl("^T\\d+$", as.character(.data$time_point_raw)) ~ as.character(.data$time_point_raw),
      TRUE ~ paste0("T", as.character(.data$time_point_raw))
    ),
    regime = paste0("A", antibiotics, " T", heat_stress, " P", parasite)
  ) %>%
  dplyr::filter(!is.na(.data$time_point)) %>%
  dplyr::filter(.data$time_point %in% timepoints)

counts_wide <- samdat %>%
  dplyr::group_by(regime, antibiotics, heat_stress, parasite, prior_stressor_history, time_point) %>%
  dplyr::summarise(n_samples = dplyr::n(), .groups = "drop") %>%
  tidyr::pivot_wider(
    names_from = time_point,
    values_from = n_samples,
    values_fill = 0
  )

for (tp in timepoints) {
  if (!tp %in% names(counts_wide)) {
    counts_wide[[tp]] <- 0L
  }
}

counts_wide <- counts_wide %>%
  dplyr::select(regime, antibiotics, heat_stress, parasite, prior_stressor_history, dplyr::all_of(timepoints))

counts_tbl <- counts_wide %>%
  dplyr::mutate(total_per_regime = rowSums(dplyr::pick(dplyr::all_of(timepoints))))

stopifnot(exists("treatment_order", inherits = TRUE))
counts_tbl <- counts_tbl %>%
  dplyr::mutate(regime = factor(.data$regime, levels = get("treatment_order", inherits = TRUE))) %>%
  dplyr::arrange(.data$regime) %>%
  dplyr::mutate(regime = as.character(.data$regime))

totals <- counts_tbl %>%
  dplyr::summarise(
    regime = "TOTAL (all regimes)",
    antibiotics = "",
    heat_stress = "",
    parasite = "",
    prior_stressor_history = NA_integer_,
    dplyr::across(dplyr::all_of(timepoints), ~ sum(.x)),
    total_per_regime = sum(total_per_regime)
  )

counts_tbl <- dplyr::bind_rows(counts_tbl, totals)

col_abx <- "#4A86C5"
col_heat <- "#E39A3B"
col_par <- "#C83C3C"
col_off <- "#FFFFFF"
col_on_text <- "#FFFFFF"
col_off_text <- "#111111"

stopifnot(
  exists("treatment_color_scale", inherits = TRUE),
  exists("history_colors", inherits = TRUE)
)

col_regime <- get("treatment_color_scale", inherits = TRUE)
col_history <- c(
  `0` = unname(get("history_colors", inherits = TRUE)[["No prior stressors"]]),
  `1` = unname(get("history_colors", inherits = TRUE)[["One prior stressor"]]),
  `2` = unname(get("history_colors", inherits = TRUE)[["Two prior stressors"]])
)

gt_tbl <- gt::gt(counts_tbl) %>%
  gt::tab_header(
    title = "Samples collected by exposure regime and time point",
    subtitle = "Counts are the number of samples in `ps.list$All`, summarized by exposure regime × timepoint"
  ) %>%
  gt::cols_label(
    regime = "Exposure regime",
    prior_stressor_history = "Prior stressor history",
    antibiotics = "Antibiotics",
    heat_stress = "Heat stress",
    parasite = "Parasite",
    total_per_regime = "Total (all timepoints)"
  ) %>%
  gt::cols_align(align = "center", columns = dplyr::all_of(c("antibiotics", "heat_stress", "parasite", "prior_stressor_history", timepoints, "total_per_regime"))) %>%
  gt::cols_align(align = "left", columns = dplyr::all_of("regime")) %>%
  gt::fmt_missing(columns = dplyr::all_of("prior_stressor_history"), missing_text = "") %>%
  gt::tab_options(table.font.size = "small")

for (nm in names(col_regime)) {
  gt_tbl <- gt_tbl %>%
    gt::tab_style(
      style = gt::cell_fill(color = unname(col_regime[[nm]])),
      locations = gt::cells_body(columns = dplyr::all_of("regime"), rows = regime == nm)
    )
}

gt_tbl <- gt_tbl %>%
  gt::tab_style(
    style = gt::cell_text(color = col_on_text, weight = "bold"),
    locations = gt::cells_body(columns = dplyr::all_of("regime"), rows = regime != "TOTAL (all regimes)")
  )

for (k in names(col_history)) {
  gt_tbl <- gt_tbl %>%
    gt::tab_style(
      style = gt::cell_fill(color = unname(col_history[[k]])),
      locations = gt::cells_body(columns = dplyr::all_of("prior_stressor_history"), rows = .data$prior_stressor_history == as.integer(k))
    )
}

gt_tbl <- gt_tbl %>%
  gt::tab_style(
    style = gt::cell_text(color = col_on_text, weight = "bold"),
    locations = gt::cells_body(columns = dplyr::all_of("prior_stressor_history"), rows = !is.na(.data$prior_stressor_history))
  )

gt_tbl <- gt_tbl %>%
  gt::tab_style(style = gt::cell_fill(color = col_abx), locations = gt::cells_body(columns = dplyr::all_of("antibiotics"), rows = antibiotics == "+")) %>%
  gt::tab_style(style = gt::cell_text(color = col_on_text, weight = "bold"), locations = gt::cells_body(columns = dplyr::all_of("antibiotics"), rows = antibiotics == "+")) %>%
  gt::tab_style(style = gt::cell_fill(color = col_off), locations = gt::cells_body(columns = dplyr::all_of("antibiotics"), rows = antibiotics == "-")) %>%
  gt::tab_style(style = gt::cell_text(color = col_off_text, weight = "bold"), locations = gt::cells_body(columns = dplyr::all_of("antibiotics"), rows = antibiotics == "-")) %>%
  gt::tab_style(style = gt::cell_fill(color = col_heat), locations = gt::cells_body(columns = dplyr::all_of("heat_stress"), rows = heat_stress == "+")) %>%
  gt::tab_style(style = gt::cell_text(color = col_on_text, weight = "bold"), locations = gt::cells_body(columns = dplyr::all_of("heat_stress"), rows = heat_stress == "+")) %>%
  gt::tab_style(style = gt::cell_fill(color = col_off), locations = gt::cells_body(columns = dplyr::all_of("heat_stress"), rows = heat_stress == "-")) %>%
  gt::tab_style(style = gt::cell_text(color = col_off_text, weight = "bold"), locations = gt::cells_body(columns = dplyr::all_of("heat_stress"), rows = heat_stress == "-")) %>%
  gt::tab_style(style = gt::cell_fill(color = col_par), locations = gt::cells_body(columns = dplyr::all_of("parasite"), rows = parasite == "+")) %>%
  gt::tab_style(style = gt::cell_text(color = col_on_text, weight = "bold"), locations = gt::cells_body(columns = dplyr::all_of("parasite"), rows = parasite == "+")) %>%
  gt::tab_style(style = gt::cell_fill(color = col_off), locations = gt::cells_body(columns = dplyr::all_of("parasite"), rows = parasite == "-")) %>%
  gt::tab_style(style = gt::cell_text(color = col_off_text, weight = "bold"), locations = gt::cells_body(columns = dplyr::all_of("parasite"), rows = parasite == "-"))

gt_tbl <- gt_tbl %>%
  gt::tab_style(
    style = list(gt::cell_text(weight = "bold"), gt::cell_fill(color = "#F2F2F2")),
    locations = gt::cells_body(rows = regime == "TOTAL (all regimes)")
  )

bundle <- list(
  meta = list(
    created_by = "Michael Sieler",
    date_last_updated = "2026-04-22",
    script = "Code/01__Analysis/00__Overview.R",
    ps_list_element = "All",
    timepoints = timepoints
  ),
  tables_tidy = list(sample_counts = counts_tbl),
  table_sample_counts = gt_tbl,
  paths = list(
    stats_dir = file.path("Results", "00__Overview", "Stats")
  )
)

saveRDS(bundle, bundle_rds)
message("Saved overview bundle -> ", bundle_rds)

